version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - ../_data/keycloak/db:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
    ports:
      - 18080:8080
      - 18443:8443
